version: '3'
services:
  backend:
    build:
      context: ./backend
    ports:
      - "6123:4000"
    networks:
      - app-network
    environment:
      - FRONTEND_URL=http://localhost:5173
      - SPACE=k9voop8uf94b
      - ENVIRONMENT=dev-1
      - CDA_TOKEN=dVkwzvA0LUKDn83NgGkvwo_HMf9rV8TzfWjpd6nJizI
      - CMA_TOKEN=CFPAT-oKXVDf5KTLpnloDucgN-TvF3du8LXh2gThaxsRWkwqc

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:5173"
    networks:
      - app-network
    environment:
      - VITE_API_URL=http://localhost:6123/api # Asegúrate de que esto coincida con el puerto en el backend

networks:
  app-network:
    driver: bridge
